// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA17XcrNwDfrd_2imwJPo6jhaDcWlnrPT8',
    appId: '1:503974047657:web:c46490fb880f234f341eb8',
    messagingSenderId: '503974047657',
    projectId: 'kukinar-86d6a',
    authDomain: 'kukinar-86d6a.firebaseapp.com',
    storageBucket: 'kukinar-86d6a.appspot.com',
    measurementId: 'G-CSC5ZZCN36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5TTWYHbPSOQsN0_BEowMDXk9CKlSSHAs',
    appId: '1:503974047657:android:9a821f57a004b38e341eb8',
    messagingSenderId: '503974047657',
    projectId: 'kukinar-86d6a',
    storageBucket: 'kukinar-86d6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9A1GQsNxkZqHSKf4R1C__Qj51MSJDOTc',
    appId: '1:503974047657:ios:9ed02aa54f3a32b2341eb8',
    messagingSenderId: '503974047657',
    projectId: 'kukinar-86d6a',
    storageBucket: 'kukinar-86d6a.appspot.com',
    iosBundleId: 'com.example.kulunar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9A1GQsNxkZqHSKf4R1C__Qj51MSJDOTc',
    appId: '1:503974047657:ios:291db8aa2486d3fb341eb8',
    messagingSenderId: '503974047657',
    projectId: 'kukinar-86d6a',
    storageBucket: 'kukinar-86d6a.appspot.com',
    iosBundleId: 'com.example.kulunar.RunnerTests',
  );
}
